spring:
  application:
    name: messengers-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeremy-vb/church-config.git
          default-label: main
          clone-on-start: true
server:
  port: 8888